from django.apps import apps
from django.core.management.base import BaseCommand, CommandError
import csv

from django.db import DataError

# PROPOSED COMMAND - python manage.py impordata - filepath modelname

class Command(BaseCommand):
    help = "This imports data from CSV file"
    
    def add_arguments(self, parser):
        parser.add_argument('file_path', type=str, help='Indicates the path to the CSV file.')
        parser.add_argument('model_name', type=str, help='Indicates the name of the Model')
    
    def handle(self, *args, **kwargs):
        # logic goes here
        file_path = kwargs['file_path']
        model_name = kwargs['model_name'].capitalize()
        
        # Search for model in all installed apps
        model = None
        
        for app_config in apps.get_app_configs(): # Loops through apps
            # Try to search for the model
            try:
                model = apps.get_model(app_config.label, model_name) # Get Model
                break #stop searching once the model is found
            except LookupError:
                continue # continue searching to another app. Because Model was not found in that app iterated on app_config
            
        if not model:
            raise CommandError(f'Model: {model_name} , not found in any app.')
        
        
        # get all the field names of the model that we found
        model_fields = [field.name for field in model._meta.fields if field.name != 'id'] # exclude id field generated by default
        print(model_fields)
        
        # WE NEED TO EXCLUDE id because it is put by default from the database but that is not included in our CSV nor in MODELS.
        with open(file_path, 'r') as file:
            reader = csv.DictReader(file) # Considers the first row as CSV header
            csv_header = reader.fieldnames # 
            
           # compare CSV header with model's field names
            if csv_header != model_fields:
               raise DataError(f'CSV file does not match with the {model_name} table fields')
           
            for row in reader:
                if not model.objects.filter(**row).exists(): # Check if that record already exists.
                    model.objects.create(**row)
                else:
                    self.stdout.write(self.style.WARNING(f"Data: {row} already exists"))
        
        self.stdout.write(self.style.SUCCESS("Data imported from CSV successfully"))
        
        
        
        
# For just one MODEL:


# class Command(BaseCommand):
#     help = "This imports data from CSV file"
    
#     def add_arguments(self, parser):
#         parser.add_argument('file_path', type=str, help='Indicates the path to the CSV file.')
    
#     def handle(self, *args, **kwargs):
#         # logic goes here
#         file_path = kwargs['file_path']
#         with open(file_path, 'r') as file:
#             reader = csv.DictReader(file)
#             for row in reader:
#                 roll_no = row['roll_no']
#                 # Student.objects.create(roll_no = row['roll_no'], name=row['name'], age=row['age']) instead we can do:
#                 # **row will match every value on dictionaries with database columns but the CSV has to be matched in columns
#                 existing_roll_no = Student.objects.filter(roll_no = roll_no).exists()
#                 if not existing_roll_no:
#                     Student.objects.create(**row)
#                 else:
#                     self.stdout.write(self.style.WARNING(f"Data with roll_no: {roll_no} already exists."))
        
#         self.stdout.write(self.style.SUCCESS("Data imported from CSV successfully"))
            
        
