# Generated by Django 5.0.6 on 2024-07-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
