# Generated by Django 5.0.6 on 2024-07-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='pe_ratio',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
