# Generated by Django 5.0.6 on 2024-07-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0003_stockdata_pe_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'verbose_name_plural': 'StockData'},
        ),
    ]
